language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO=Django==1.4.2
  - DJANGO=Django==1.5.0
  - DJANGO=https://github.com/django/django/tarball/stable/1.6.x

install:
  - pip install --use-mirrors $DJANGO
  - pip install --use-mirrors coverage coveralls

script: coverage run setup.py test

after_success: coveralls

matrix:
  exclude:
   - python: 3.3
     env: DJANGO=Django==1.4.2
   - python: 3.4
     env: DJANGO=Django==1.4.2
